version: '3.9'

services:
  backend:
    build:
      context: ./hotel-booking-backend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/hotel-booking
    volumes:
      - ./hotel-booking-backend:/app
    depends_on:
      - mongo
    command: npm run start:dev

  frontend:
    build:
      context: ./hotel-booking-frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./hotel-booking-frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
      - NODE_ENV=development
    stdin_open: true
    tty: true
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: